version: 2.1

jobs:
  test:
    machine:
      docker_layer_caching: false
    working_directory: ~/codeclimate/codeclimate-checkstyle
    steps:
      - checkout
      - run: make image
      - run: make test

  release_images:
    machine:
      docker_layer_caching: false
    working_directory: ~/codeclimate/codeclimate-checkstyle
    steps:
      - checkout
      - run:
          name: Validate owner
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" -ne "codeclimate" ]
            then
              echo "Skipping release for non-codeclimate branches"
              circleci step halt
            fi
      - run: make image
      - run: echo "$GCR_JSON_KEY" | docker login -u _json_key --password-stdin us.gcr.io
      - run:
          name: Push image to GCR
          command: |
            docker tag codeclimate/codeclimate-checkstyle \
              us.gcr.io/code-climate/codeclimate-checkstyle:b$CIRCLE_BUILD_NUM
            docker push us.gcr.io/code-climate/codeclimate-checkstyle:b$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build_deploy:
    jobs:
      - test
      - release_images:
          context: Quality
          requires:
            - test
          filters:
            branches:
              only: /master|channel\/[\w-]+/
notify:
  webhooks:
    - url: https://cc-slack-proxy.herokuapp.com/circle
